import { GetStaticProps } from "next";
import { Params } from "next/dist/next-server/server/router";
import Head from "next/head";
import React from "react";
import Image from "next/image";
import Duplicator from "../components/duplicator";
import styles from "../styles/Home.module.css";

interface HomeProps {
  id: string;
}

export default function Home(props: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Duplicator id={props.id} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps: GetStaticProps<HomeProps, Params["params"]> = async ({
  params,
}: Params) => {
  return {
    props: {
      id: "test",
    },
  };
};
